{% set name = "python-slugify" %}
{% set version = "9.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-slugify/python_slugify-9.1.0.tar.gz
    sha256: 3f02e8a0639c61e37eca5a783aae09112796d15d331ee3d5372241b61ee05f1c
  - url: https://github.com/un33k/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0a14bf38e44e26af1e1fb76c00818bb89446261187791d061d6d70d0eae2c244
    folder: gh

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - slugify=slugify.__main__:main
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - text-unidecode >=1.3
  run_constrained:
    - unidecode >=1.1.1

test:
  requires:
    - pip
  imports:
    - slugify
  source_files:
    - gh/test.py
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - slugify --help
    - python -m unittest -v gh/test.py

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  description: A Python slugify application that handles unicode.
  dev_url: https://github.com/un33k/python-slugify
  doc_url: https://github.com/un33k/python-slugify/blob/master/README.md

extra:
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
