{% set name = "python-slugify" %}
{% set version = "3.0.2" %}
{% set sha256 = "57163ffb345c7e26063435a27add1feae67fa821f1ef4b2f292c25847575d758" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - fix_command.patch

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - slugify = slugify.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - unidecode >=0.04.16

test:
  imports:
    - slugify

  commands:
    - slugify --help


about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  # license_file: LICENSE There is no license in python-slugify
  summary: 'A Python Slugify application that handles Unicode'
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
