travis:
  secure:
    BINSTAR_TOKEN: MJMJFh6pvavwvTMzp2FvqQZH6cMOZkeYVJ8tJGrFWRpvm6Nd2KrLTfJFosqdEOCcNX74PZSgz7bEU8/fHRr7JQgoV127kk97SIolJH/ZM/GG0nRVGLHg6EIHEaruK3EOovvvMIJ5VeiI+b8xI0bxEn5TUQPQWyyg3fC25O4Ra6h0VkAIdXFSXOv71abPBdvsRdQbyOU1cc0Tb0+2/n61FKwx4fZed1T0EOcussQc9jeONIOvV8AvlvJtBqkswgIt+0/9MS3JjAiQVjWREsYjSzHNKFz+xCcmpqOmQAuTn74GWJdhUewIIv1RENUAelmnKXmttxArCVLs5xSoe7gvaMGauXuXXijkyKFTx7CR3Kuppbbs58sca5WMneAh9NTqbV+Uj6eFEgLUH3LvBArHwxg9Zq81FniyEpH3b86tSBD+HtvU4X84FYeQ8RInvMPg/XQo6KqICf0ljfUGTGwy8XrRHDhwNiLlDY88+hB97kZuhtsuy+coDsG5OSQWHZqURPyV8OK9QDIpRbYx/5kj+tkaQpaw/TfLQAj5Dcxk2QlqYnoJMf7okH/2lyIm4XBjjjD1mkHv2iNH/q+bJZbi/PEEdQyoEPlBdkKxvYNMllOgMbe2WszV7mPEcGL7/+qXSdsuOdR4HARYNfRGSuj0LCA8ioTKO0PH4mcW+IJXAXU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
