travis:
  secure:
    BINSTAR_TOKEN: IYsDMf2F6ySK3EE2hvn1jkxfiP13cs7fgZL05PWNCVyfvedFTInP3mx2uFguvL4q/+If9PtB9n202O0Jb2u+MghMOvww/X9Ln00R3jilXsMPOZFSW064jYEbgaFCNUsWWzy2z2bSV7IbNuPtxDQw6kLxmzopKoSBCyXSeaL3U7hsaXu82aXqvP/CTkQXsQ0C42g9rulQrbq/RA3cfxoBwHoOyqLJqleTSeEakaBcp6yF8whUn5sP9KP3yWKPDOOKxl/kdYkIxcPrt1VJMR/L9udgUCTctnUQhYGZ2Tkd3VF3gOX+DevcUCeAdo2VAsldnXMd8nzse//z/lu5PB9A02NhuYlMABxeUSbcbkM+/jgiKzG9BrAUT54G5rxFDEQapy32lXMyobdoPbPqdHxvRiqkJvdvsdURL4SJ8OVtNz/RYUtjbMbQBtCU+LKSlf932JMnBWAsNhY1n1MW3v6e3Avh68/s5uvKT8GaPk8nTs/XYBoeBSvhtMfo3Vry+pCOANwbBDOHQx0M7UgfBSqieTOT0/TUzgtn6PISD+iOlIb9E8pcyuXxAfmUqq7tO6EfLbHEyry0JP4+Pb4v+geVLGCVchcsjK1ET81b3+PDPGyXZiYF7Jgy7Yx2E2/XAAcEgX8dBjuhul9ncCEuEOnohXQmYDnXf07UIPjS1hbYRsI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
